name: google-java-format
on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v4
        with:
          release-name: "v1.24.0"
          args: "--replace"
          commit-message: "style: google-java-format"
